// Auto-generated by prismatica xtask -- do not edit
//! d3-scale-chromatic colormaps.
//!
//! Colormaps from Mike Bostock's d3-scale-chromatic, the colour
//! scheme module of the D3.js visualization library.
//!
//! Source: <https://github.com/d3/d3-scale-chromatic>

mod cool;
pub use cool::COOL;
mod cubehelixdefault;
pub use cubehelixdefault::CUBEHELIXDEFAULT;
mod rainbow;
pub use rainbow::RAINBOW;
mod sinebow;
pub use sinebow::SINEBOW;
mod tableau10;
pub use tableau10::TABLEAU10;
mod turbo;
pub use turbo::TURBO;
mod warm;
pub use warm::WARM;
pub use tableau10::TABLEAU10_PALETTE;

/// All colormaps in the d3 collection.
pub static ALL: &[&crate::Colormap] = &[
    &COOL,
    &CUBEHELIXDEFAULT,
    &RAINBOW,
    &SINEBOW,
    &TABLEAU10,
    &TURBO,
    &WARM,
];

/// All discrete palettes in the d3 collection.
pub static ALL_DISCRETE: &[&crate::DiscretePalette] = &[
    &TABLEAU10_PALETTE,
];
