// Auto-generated by prismatica xtask -- do not edit
//! CMasher colormaps for astrophysics visualization (30+ sequential and diverging maps).
//!
//! Ellert van der Velden's colormaps designed for astrophysical
//! data visualization, with strong emphasis on perceptual uniformity
//! and accessibility.
//!
//! License: BSD-3.
//!
//! Source: <https://github.com/1313e/CMasher>
//!
//! Citation: van der Velden, E. (2020). CMasher: Scientific colormaps
//! for making accessible, informative and 'cmashing' plots. JOSS, 5(46), 2004.

mod amber;
pub use amber::AMBER;

mod amethyst;
pub use amethyst::AMETHYST;

mod apple;
pub use apple::APPLE;

mod arctic;
pub use arctic::ARCTIC;

mod bubblegum;
pub use bubblegum::BUBBLEGUM;

mod chroma;
pub use chroma::CHROMA;

mod copper;
pub use copper::COPPER;

mod cosmic;
pub use cosmic::COSMIC;

mod dusk;
pub use dusk::DUSK;

mod eclipse;
pub use eclipse::ECLIPSE;

mod ember;
pub use ember::EMBER;

mod emerald;
pub use emerald::EMERALD;

mod emergency;
pub use emergency::EMERGENCY;

mod fall;
pub use fall::FALL;

mod flamingo;
pub use flamingo::FLAMINGO;

mod freeze;
pub use freeze::FREEZE;

mod fusion;
pub use fusion::FUSION;

mod gem;
pub use gem::GEM;

mod ghostlight;
pub use ghostlight::GHOSTLIGHT;

mod gothic;
pub use gothic::GOTHIC;

mod guppy;
pub use guppy::GUPPY;

mod holly;
pub use holly::HOLLY;

mod horizon;
pub use horizon::HORIZON;

mod iceburn;
pub use iceburn::ICEBURN;

mod infinity;
pub use infinity::INFINITY;

mod jungle;
pub use jungle::JUNGLE;

mod lavender;
pub use lavender::LAVENDER;

mod lilac;
pub use lilac::LILAC;

mod neon;
pub use neon::NEON;

mod neutral;
pub use neutral::NEUTRAL;

mod nuclear;
pub use nuclear::NUCLEAR;

mod ocean;
pub use ocean::OCEAN;

mod pepper;
pub use pepper::PEPPER;

mod pride;
pub use pride::PRIDE;

mod prinsenvlag;
pub use prinsenvlag::PRINSENVLAG;

mod rainforest;
pub use rainforest::RAINFOREST;

mod redshift;
pub use redshift::REDSHIFT;

mod sapphire;
pub use sapphire::SAPPHIRE;

mod savanna;
pub use savanna::SAVANNA;

mod seasons;
pub use seasons::SEASONS;

mod seaweed;
pub use seaweed::SEAWEED;

mod sepia;
pub use sepia::SEPIA;

mod sunburst;
pub use sunburst::SUNBURST;

mod swamp;
pub use swamp::SWAMP;

mod torch;
pub use torch::TORCH;

mod toxic;
pub use toxic::TOXIC;

mod tree;
pub use tree::TREE;

mod tropical;
pub use tropical::TROPICAL;

mod viola;
pub use viola::VIOLA;

mod voltage;
pub use voltage::VOLTAGE;

mod waterlily;
pub use waterlily::WATERLILY;

mod watermelon;
pub use watermelon::WATERMELON;

mod wildfire;
pub use wildfire::WILDFIRE;

/// All colormaps in the cmasher collection.
pub static ALL: &[&crate::Colormap] = &[
    &AMBER,
    &AMETHYST,
    &APPLE,
    &ARCTIC,
    &BUBBLEGUM,
    &CHROMA,
    &COPPER,
    &COSMIC,
    &DUSK,
    &ECLIPSE,
    &EMBER,
    &EMERALD,
    &EMERGENCY,
    &FALL,
    &FLAMINGO,
    &FREEZE,
    &FUSION,
    &GEM,
    &GHOSTLIGHT,
    &GOTHIC,
    &GUPPY,
    &HOLLY,
    &HORIZON,
    &ICEBURN,
    &INFINITY,
    &JUNGLE,
    &LAVENDER,
    &LILAC,
    &NEON,
    &NEUTRAL,
    &NUCLEAR,
    &OCEAN,
    &PEPPER,
    &PRIDE,
    &PRINSENVLAG,
    &RAINFOREST,
    &REDSHIFT,
    &SAPPHIRE,
    &SAVANNA,
    &SEASONS,
    &SEAWEED,
    &SEPIA,
    &SUNBURST,
    &SWAMP,
    &TORCH,
    &TOXIC,
    &TREE,
    &TROPICAL,
    &VIOLA,
    &VOLTAGE,
    &WATERLILY,
    &WATERMELON,
    &WILDFIRE,
];
