// Auto-generated by prismatica xtask -- do not edit
//! Crameri Scientific Colour Maps -- 40 colormaps.
//!
//! Includes batlow, berlin, roma, oslo, tokyo, hawaii, and more.
//!
//! Fabio Crameri's perceptually uniform, CVD-friendly, and
//! order-able colormaps designed for geoscience and general
//! scientific visualization. These are the maps that Nature
//! Communications now mandates for data figures.
//!
//! License: MIT.
//!
//! Source: <https://zenodo.org/records/8409685>
//!
//! Citation: Crameri, F. (2018). Scientific colour maps. Zenodo.
//! <https://doi.org/10.5281/zenodo.1243862>

mod acton;
pub use acton::ACTON;

mod bam;
pub use bam::BAM;

mod bamako;
pub use bamako::BAMAKO;

mod bamo;
pub use bamo::BAMO;

mod batlow;
pub use batlow::BATLOW;

mod batlowk;
pub use batlowk::BATLOWK;

mod batloww;
pub use batloww::BATLOWW;

mod berlin;
pub use berlin::BERLIN;

mod bilbao;
pub use bilbao::BILBAO;

mod broc;
pub use broc::BROC;

mod broco;
pub use broco::BROCO;

mod buda;
pub use buda::BUDA;

mod bukavu;
pub use bukavu::BUKAVU;

mod cork;
pub use cork::CORK;

mod corko;
pub use corko::CORKO;

mod davos;
pub use davos::DAVOS;

mod devon;
pub use devon::DEVON;

mod fes;
pub use fes::FES;

mod glasgow;
pub use glasgow::GLASGOW;

mod grayc;
pub use grayc::GRAYC;

mod hawaii;
pub use hawaii::HAWAII;

mod imola;
pub use imola::IMOLA;

mod lajolla;
pub use lajolla::LAJOLLA;

mod lapaz;
pub use lapaz::LAPAZ;

mod lipari;
pub use lipari::LIPARI;

mod lisbon;
pub use lisbon::LISBON;

mod managua;
pub use managua::MANAGUA;

mod navia;
pub use navia::NAVIA;

mod naviaw;
pub use naviaw::NAVIAW;

mod nuuk;
pub use nuuk::NUUK;

mod oleron;
pub use oleron::OLERON;

mod oslo;
pub use oslo::OSLO;

mod roma;
pub use roma::ROMA;

mod romao;
pub use romao::ROMAO;

mod tofino;
pub use tofino::TOFINO;

mod tokyo;
pub use tokyo::TOKYO;

mod turku;
pub use turku::TURKU;

mod vanimo;
pub use vanimo::VANIMO;

mod vik;
pub use vik::VIK;

mod viko;
pub use viko::VIKO;

/// All colormaps in the crameri collection.
pub static ALL: &[&crate::Colormap] = &[
    &ACTON, &BAM, &BAMAKO, &BAMO, &BATLOW, &BATLOWK, &BATLOWW, &BERLIN, &BILBAO, &BROC, &BROCO,
    &BUDA, &BUKAVU, &CORK, &CORKO, &DAVOS, &DEVON, &FES, &GLASGOW, &GRAYC, &HAWAII, &IMOLA,
    &LAJOLLA, &LAPAZ, &LIPARI, &LISBON, &MANAGUA, &NAVIA, &NAVIAW, &NUUK, &OLERON, &OSLO, &ROMA,
    &ROMAO, &TOFINO, &TOKYO, &TURKU, &VANIMO, &VIK, &VIKO,
];
