// Auto-generated by prismatica xtask -- do not edit
//! CartoColors cartographic colormaps -- 34 colormaps + 34 discrete palettes.
//!
//! CARTO's data-driven colour schemes. Access palettes via [`ALL_DISCRETE`].
//!
//! License: CC-BY-3.0.
//!
//! Source: <https://carto.com/carto-colors/>

mod ag_grnyl;
pub use ag_grnyl::AG_GRNYL;
mod ag_sunset;
pub use ag_sunset::AG_SUNSET;
mod antique;
pub use antique::ANTIQUE;
mod armyrose;
pub use armyrose::ARMYROSE;
mod blugrn;
pub use blugrn::BLUGRN;
mod bluyl;
pub use bluyl::BLUYL;
mod bold;
pub use bold::BOLD;
mod brwnyl;
pub use brwnyl::BRWNYL;
mod burg;
pub use burg::BURG;
mod burgyl;
pub use burgyl::BURGYL;
mod darkmint;
pub use darkmint::DARKMINT;
mod earth;
pub use earth::EARTH;
mod emrld;
pub use emrld::EMRLD;
mod fall;
pub use fall::FALL;
mod geyser;
pub use geyser::GEYSER;
mod magenta;
pub use magenta::MAGENTA;
mod mint;
pub use mint::MINT;
mod oryel;
pub use oryel::ORYEL;
mod pastel;
pub use pastel::PASTEL;
mod peach;
pub use peach::PEACH;
mod pinkyl;
pub use pinkyl::PINKYL;
mod prism;
pub use prism::PRISM;
mod purp;
pub use purp::PURP;
mod purpor;
pub use purpor::PURPOR;
mod redor;
pub use redor::REDOR;
mod safe;
pub use safe::SAFE;
mod sunset;
pub use sunset::SUNSET;
mod sunsetdark;
pub use sunsetdark::SUNSETDARK;
mod teal;
pub use teal::TEAL;
mod tealgrn;
pub use tealgrn::TEALGRN;
mod tealrose;
pub use tealrose::TEALROSE;
mod temps;
pub use temps::TEMPS;
mod tropic;
pub use tropic::TROPIC;
mod vivid;
pub use ag_grnyl::AG_GRNYL_PALETTE;
pub use ag_sunset::AG_SUNSET_PALETTE;
pub use antique::ANTIQUE_PALETTE;
pub use armyrose::ARMYROSE_PALETTE;
pub use blugrn::BLUGRN_PALETTE;
pub use bluyl::BLUYL_PALETTE;
pub use bold::BOLD_PALETTE;
pub use brwnyl::BRWNYL_PALETTE;
pub use burg::BURG_PALETTE;
pub use burgyl::BURGYL_PALETTE;
pub use darkmint::DARKMINT_PALETTE;
pub use earth::EARTH_PALETTE;
pub use emrld::EMRLD_PALETTE;
pub use fall::FALL_PALETTE;
pub use geyser::GEYSER_PALETTE;
pub use magenta::MAGENTA_PALETTE;
pub use mint::MINT_PALETTE;
pub use oryel::ORYEL_PALETTE;
pub use pastel::PASTEL_PALETTE;
pub use peach::PEACH_PALETTE;
pub use pinkyl::PINKYL_PALETTE;
pub use prism::PRISM_PALETTE;
pub use purp::PURP_PALETTE;
pub use purpor::PURPOR_PALETTE;
pub use redor::REDOR_PALETTE;
pub use safe::SAFE_PALETTE;
pub use sunset::SUNSET_PALETTE;
pub use sunsetdark::SUNSETDARK_PALETTE;
pub use teal::TEAL_PALETTE;
pub use tealgrn::TEALGRN_PALETTE;
pub use tealrose::TEALROSE_PALETTE;
pub use temps::TEMPS_PALETTE;
pub use tropic::TROPIC_PALETTE;
pub use vivid::VIVID;
pub use vivid::VIVID_PALETTE;

/// All colormaps in the cartocolors collection.
pub static ALL: &[&crate::Colormap] = &[
    &AG_GRNYL,
    &AG_SUNSET,
    &ANTIQUE,
    &ARMYROSE,
    &BLUGRN,
    &BLUYL,
    &BOLD,
    &BRWNYL,
    &BURG,
    &BURGYL,
    &DARKMINT,
    &EARTH,
    &EMRLD,
    &FALL,
    &GEYSER,
    &MAGENTA,
    &MINT,
    &ORYEL,
    &PASTEL,
    &PEACH,
    &PINKYL,
    &PRISM,
    &PURP,
    &PURPOR,
    &REDOR,
    &SAFE,
    &SUNSET,
    &SUNSETDARK,
    &TEAL,
    &TEALGRN,
    &TEALROSE,
    &TEMPS,
    &TROPIC,
    &VIVID,
];

/// All discrete palettes in the cartocolors collection.
pub static ALL_DISCRETE: &[&crate::DiscretePalette] = &[
    &AG_GRNYL_PALETTE,
    &AG_SUNSET_PALETTE,
    &ANTIQUE_PALETTE,
    &ARMYROSE_PALETTE,
    &BLUGRN_PALETTE,
    &BLUYL_PALETTE,
    &BOLD_PALETTE,
    &BRWNYL_PALETTE,
    &BURG_PALETTE,
    &BURGYL_PALETTE,
    &DARKMINT_PALETTE,
    &EARTH_PALETTE,
    &EMRLD_PALETTE,
    &FALL_PALETTE,
    &GEYSER_PALETTE,
    &MAGENTA_PALETTE,
    &MINT_PALETTE,
    &ORYEL_PALETTE,
    &PASTEL_PALETTE,
    &PEACH_PALETTE,
    &PINKYL_PALETTE,
    &PRISM_PALETTE,
    &PURP_PALETTE,
    &PURPOR_PALETTE,
    &REDOR_PALETTE,
    &SAFE_PALETTE,
    &SUNSET_PALETTE,
    &SUNSETDARK_PALETTE,
    &TEAL_PALETTE,
    &TEALGRN_PALETTE,
    &TEALROSE_PALETTE,
    &TEMPS_PALETTE,
    &TROPIC_PALETTE,
    &VIVID_PALETTE,
];
