// Auto-generated by prismatica xtask -- do not edit
//! CMOcean oceanographic colormaps (thermal, haline, solar, ice, deep, and 17 more).
//!
//! Kristen Thyng's perceptually uniform colormaps designed for
//! oceanographic data. Each map is tailored to a specific
//! oceanographic variable (temperature, salinity, bathymetry, etc.).
//!
//! License: MIT.
//!
//! Source: <https://github.com/matplotlib/cmocean>
//!
//! Citation: Thyng, K. M. et al. (2016). True colors of oceanography.
//! Oceanography, 29(3), 10.

mod algae;
pub use algae::ALGAE;

mod amp;
pub use amp::AMP;

mod balance;
pub use balance::BALANCE;

mod curl;
pub use curl::CURL;

mod deep;
pub use deep::DEEP;

mod delta;
pub use delta::DELTA;

mod dense;
pub use dense::DENSE;

mod diff;
pub use diff::DIFF;

mod gray;
pub use gray::GRAY;

mod haline;
pub use haline::HALINE;

mod ice;
pub use ice::ICE;

mod matter;
pub use matter::MATTER;

mod oxy;
pub use oxy::OXY;

mod phase;
pub use phase::PHASE;

mod rain;
pub use rain::RAIN;

mod solar;
pub use solar::SOLAR;

mod speed;
pub use speed::SPEED;

mod tarn;
pub use tarn::TARN;

mod tempo;
pub use tempo::TEMPO;

mod thermal;
pub use thermal::THERMAL;

mod topo;
pub use topo::TOPO;

mod turbid;
pub use turbid::TURBID;

/// All colormaps in the cmocean collection.
pub static ALL: &[&crate::Colormap] = &[
    &ALGAE, &AMP, &BALANCE, &CURL, &DEEP, &DELTA, &DENSE, &DIFF, &GRAY, &HALINE, &ICE, &MATTER,
    &OXY, &PHASE, &RAIN, &SOLAR, &SPEED, &TARN, &TEMPO, &THERMAL, &TOPO, &TURBID,
];
