// Auto-generated by prismatica xtask -- do not edit
//! Moreland colormaps (cool-warm, black body, Kindlmann, and variants).
//!
//! Kenneth Moreland's carefully designed diverging and sequential
//! colormaps, developed for scientific visualization in ParaView
//! and VTK. The cool-warm diverging map is a widely recommended
//! alternative to red-blue schemes.
//!
//! License: Public domain / BSD.
//!
//! Source: <https://www.kennethmoreland.com/color-advice/>

mod bent_cool_warm;
pub use bent_cool_warm::BENT_COOL_WARM;

mod black_body;
pub use black_body::BLACK_BODY;

mod extended_kindlmann;
pub use extended_kindlmann::EXTENDED_KINDLMANN;

mod fast;
pub use fast::FAST;

mod kindlmann;
pub use kindlmann::KINDLMANN;

mod smooth_cool_warm;
pub use smooth_cool_warm::SMOOTH_COOL_WARM;

/// All colormaps in the moreland collection.
pub static ALL: &[&crate::Colormap] = &[
    &BENT_COOL_WARM,
    &BLACK_BODY,
    &EXTENDED_KINDLMANN,
    &FAST,
    &KINDLMANN,
    &SMOOTH_COOL_WARM,
];
