// Auto-generated by prismatica xtask -- do not edit
//! ColorBrewer palettes (sequential, diverging, and qualitative cartographic schemes).
//!
//! Cynthia Brewer's cartographic color schemes, the gold standard
//! for thematic maps. Includes both discrete palettes (original
//! 3-12 step schemes) and interpolated continuous colormaps.
//!
//! License: Apache-2.0.
//!
//! Source: <https://colorbrewer2.org/>

mod accent;
pub use accent::ACCENT;
mod blues;
pub use blues::BLUES;
mod brbg;
pub use brbg::BRBG;
mod bugn;
pub use bugn::BUGN;
mod bupu;
pub use bupu::BUPU;
mod dark2;
pub use dark2::DARK2;
mod gnbu;
pub use gnbu::GNBU;
mod greens;
pub use greens::GREENS;
mod greys;
pub use greys::GREYS;
mod oranges;
pub use oranges::ORANGES;
mod orrd;
pub use orrd::ORRD;
mod paired;
pub use paired::PAIRED;
mod pastel1;
pub use pastel1::PASTEL1;
mod pastel2;
pub use pastel2::PASTEL2;
mod piyg;
pub use piyg::PIYG;
mod prgn;
pub use prgn::PRGN;
mod pubu;
pub use pubu::PUBU;
mod pubugn;
pub use pubugn::PUBUGN;
mod puor;
pub use puor::PUOR;
mod purd;
pub use purd::PURD;
mod purples;
pub use purples::PURPLES;
mod rdbu;
pub use rdbu::RDBU;
mod rdgy;
pub use rdgy::RDGY;
mod rdpu;
pub use rdpu::RDPU;
mod rdylbu;
pub use rdylbu::RDYLBU;
mod rdylgn;
pub use rdylgn::RDYLGN;
mod reds;
pub use reds::REDS;
mod set1;
pub use set1::SET1;
mod set2;
pub use set2::SET2;
mod set3;
pub use set3::SET3;
mod spectral;
pub use spectral::SPECTRAL;
mod ylgn;
pub use ylgn::YLGN;
mod ylgnbu;
pub use ylgnbu::YLGNBU;
mod ylorbr;
pub use ylorbr::YLORBR;
mod ylorrd;
pub use ylorrd::YLORRD;
pub use accent::ACCENT_PALETTE;
pub use blues::BLUES_PALETTE;
pub use brbg::BRBG_PALETTE;
pub use bugn::BUGN_PALETTE;
pub use bupu::BUPU_PALETTE;
pub use dark2::DARK2_PALETTE;
pub use gnbu::GNBU_PALETTE;
pub use greens::GREENS_PALETTE;
pub use greys::GREYS_PALETTE;
pub use oranges::ORANGES_PALETTE;
pub use orrd::ORRD_PALETTE;
pub use paired::PAIRED_PALETTE;
pub use pastel1::PASTEL1_PALETTE;
pub use pastel2::PASTEL2_PALETTE;
pub use piyg::PIYG_PALETTE;
pub use prgn::PRGN_PALETTE;
pub use pubu::PUBU_PALETTE;
pub use pubugn::PUBUGN_PALETTE;
pub use puor::PUOR_PALETTE;
pub use purd::PURD_PALETTE;
pub use purples::PURPLES_PALETTE;
pub use rdbu::RDBU_PALETTE;
pub use rdgy::RDGY_PALETTE;
pub use rdpu::RDPU_PALETTE;
pub use rdylbu::RDYLBU_PALETTE;
pub use rdylgn::RDYLGN_PALETTE;
pub use reds::REDS_PALETTE;
pub use set1::SET1_PALETTE;
pub use set2::SET2_PALETTE;
pub use set3::SET3_PALETTE;
pub use spectral::SPECTRAL_PALETTE;
pub use ylgn::YLGN_PALETTE;
pub use ylgnbu::YLGNBU_PALETTE;
pub use ylorbr::YLORBR_PALETTE;
pub use ylorrd::YLORRD_PALETTE;

/// All colormaps in the colorbrewer collection.
pub static ALL: &[&crate::Colormap] = &[
    &ACCENT,
    &BLUES,
    &BRBG,
    &BUGN,
    &BUPU,
    &DARK2,
    &GNBU,
    &GREENS,
    &GREYS,
    &ORANGES,
    &ORRD,
    &PAIRED,
    &PASTEL1,
    &PASTEL2,
    &PIYG,
    &PRGN,
    &PUBU,
    &PUBUGN,
    &PUOR,
    &PURD,
    &PURPLES,
    &RDBU,
    &RDGY,
    &RDPU,
    &RDYLBU,
    &RDYLGN,
    &REDS,
    &SET1,
    &SET2,
    &SET3,
    &SPECTRAL,
    &YLGN,
    &YLGNBU,
    &YLORBR,
    &YLORRD,
];

/// All discrete palettes in the colorbrewer collection.
pub static ALL_DISCRETE: &[&crate::DiscretePalette] = &[
    &ACCENT_PALETTE,
    &BLUES_PALETTE,
    &BRBG_PALETTE,
    &BUGN_PALETTE,
    &BUPU_PALETTE,
    &DARK2_PALETTE,
    &GNBU_PALETTE,
    &GREENS_PALETTE,
    &GREYS_PALETTE,
    &ORANGES_PALETTE,
    &ORRD_PALETTE,
    &PAIRED_PALETTE,
    &PASTEL1_PALETTE,
    &PASTEL2_PALETTE,
    &PIYG_PALETTE,
    &PRGN_PALETTE,
    &PUBU_PALETTE,
    &PUBUGN_PALETTE,
    &PUOR_PALETTE,
    &PURD_PALETTE,
    &PURPLES_PALETTE,
    &RDBU_PALETTE,
    &RDGY_PALETTE,
    &RDPU_PALETTE,
    &RDYLBU_PALETTE,
    &RDYLGN_PALETTE,
    &REDS_PALETTE,
    &SET1_PALETTE,
    &SET2_PALETTE,
    &SET3_PALETTE,
    &SPECTRAL_PALETTE,
    &YLGN_PALETTE,
    &YLGNBU_PALETTE,
    &YLORBR_PALETTE,
    &YLORRD_PALETTE,
];
