// Auto-generated by prismatica xtask -- do not edit
//! NCAR NCL geoscience colormaps -- 44 colormaps.
//!
//! Maps for atmospheric and earth science visualization.
//!
//! The NCAR Command Language (NCL) colour tables, widely used in
//! atmospheric and earth science for weather, climate, and
//! geophysical data visualization.
//!
//! License: Apache-2.0.
//!
//! Source: <https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml>

mod amwg256;
pub use amwg256::AMWG256;

mod bkblaqgryeorreviwh200;
pub use bkblaqgryeorreviwh200::BKBLAQGRYEORREVIWH200;

mod blaqgryeorre;
pub use blaqgryeorre::BLAQGRYEORRE;

mod blaqgryeorrevi200;
pub use blaqgryeorrevi200::BLAQGRYEORREVI200;

mod blgryeorrevi200;
pub use blgryeorrevi200::BLGRYEORREVI200;

mod blre;
pub use blre::BLRE;

mod blwhre;
pub use blwhre::BLWHRE;

mod gmt_cool;
pub use gmt_cool::GMT_COOL;

mod gmt_copper;
pub use gmt_copper::GMT_COPPER;

mod gmt_drywet;
pub use gmt_drywet::GMT_DRYWET;

mod gmt_gebco;
pub use gmt_gebco::GMT_GEBCO;

mod gmt_globe;
pub use gmt_globe::GMT_GLOBE;

mod gmt_gray;
pub use gmt_gray::GMT_GRAY;

mod gmt_haxby;
pub use gmt_haxby::GMT_HAXBY;

mod gmt_hot;
pub use gmt_hot::GMT_HOT;

mod gmt_jet;
pub use gmt_jet::GMT_JET;

mod gmt_ocean;
pub use gmt_ocean::GMT_OCEAN;

mod gmt_panoply;
pub use gmt_panoply::GMT_PANOPLY;

mod gmt_polar;
pub use gmt_polar::GMT_POLAR;

mod gmt_relief;
pub use gmt_relief::GMT_RELIEF;

mod gmt_seis;
pub use gmt_seis::GMT_SEIS;

mod gmt_split;
pub use gmt_split::GMT_SPLIT;

mod gmt_topo;
pub use gmt_topo::GMT_TOPO;

mod gmt_wysiwyg;
pub use gmt_wysiwyg::GMT_WYSIWYG;

mod greenmagenta16;
pub use greenmagenta16::GREENMAGENTA16;

mod hotcold_18lev;
pub use hotcold_18lev::HOTCOLD_18LEV;

mod hotcolr_19lev;
pub use hotcolr_19lev::HOTCOLR_19LEV;

mod matlab_hsv;
pub use matlab_hsv::MATLAB_HSV;

mod matlab_jet;
pub use matlab_jet::MATLAB_JET;

mod ncview_default;
pub use ncview_default::NCVIEW_DEFAULT;

mod nrl_sirkes;
pub use nrl_sirkes::NRL_SIRKES;

mod nrl_sirkes_nowhite;
pub use nrl_sirkes_nowhite::NRL_SIRKES_NOWHITE;

mod posneg_1;
pub use posneg_1::POSNEG_1;

mod precip3_16lev;
pub use precip3_16lev::PRECIP3_16LEV;

mod radar_1;
pub use radar_1::RADAR_1;

mod sunshine_9lev;
pub use sunshine_9lev::SUNSHINE_9LEV;

mod temp_19lev;
pub use temp_19lev::TEMP_19LEV;

mod temp_diff_18lev;
pub use temp_diff_18lev::TEMP_DIFF_18LEV;

mod thelix;
pub use thelix::THELIX;

mod topo_15lev;
pub use topo_15lev::TOPO_15LEV;

mod wgne15;
pub use wgne15::WGNE15;

mod whblgryere;
pub use whblgryere::WHBLGRYERE;

mod whviblgryeorre;
pub use whviblgryeorre::WHVIBLGRYEORRE;

mod whviblgryeorrewh;
pub use whviblgryeorrewh::WHVIBLGRYEORREWH;

/// All colormaps in the ncar collection.
pub static ALL: &[&crate::Colormap] = &[
    &AMWG256,
    &BKBLAQGRYEORREVIWH200,
    &BLAQGRYEORRE,
    &BLAQGRYEORREVI200,
    &BLGRYEORREVI200,
    &BLRE,
    &BLWHRE,
    &GMT_COOL,
    &GMT_COPPER,
    &GMT_DRYWET,
    &GMT_GEBCO,
    &GMT_GLOBE,
    &GMT_GRAY,
    &GMT_HAXBY,
    &GMT_HOT,
    &GMT_JET,
    &GMT_OCEAN,
    &GMT_PANOPLY,
    &GMT_POLAR,
    &GMT_RELIEF,
    &GMT_SEIS,
    &GMT_SPLIT,
    &GMT_TOPO,
    &GMT_WYSIWYG,
    &GREENMAGENTA16,
    &HOTCOLD_18LEV,
    &HOTCOLR_19LEV,
    &MATLAB_HSV,
    &MATLAB_JET,
    &NCVIEW_DEFAULT,
    &NRL_SIRKES,
    &NRL_SIRKES_NOWHITE,
    &POSNEG_1,
    &PRECIP3_16LEV,
    &RADAR_1,
    &SUNSHINE_9LEV,
    &TEMP_19LEV,
    &TEMP_DIFF_18LEV,
    &THELIX,
    &TOPO_15LEV,
    &WGNE15,
    &WHBLGRYERE,
    &WHVIBLGRYEORRE,
    &WHVIBLGRYEORREWH,
];
