use anyhow::{Context, Result, bail};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::generate;

/// All collection directories that may contain generated .rs files.
const COLLECTIONS: &[&str] = &[
    "matplotlib",
    "crameri",
    "cet",
    "cmocean",
    "colorbrewer",
    "cmasher",
    "ncar",
    "cartocolors",
    "moreland",
    "d3",
];

const GENERATED_PREAMBLE: &str = "// Auto-generated by prismatica xtask";

/// Run the check subcommand: verify that generated files are up to date.
///
/// 1. Snapshot contents of all generated .rs files in src/
/// 2. Run generate_all()
/// 3. Compare new file contents against saved contents
/// 4. If any differ, print the differences and exit with an error
/// 5. If all match, report success
pub fn run(project_root: &Path) -> Result<()> {
    println!("Checking that generated files are up to date...");

    // Step 1: snapshot all generated .rs file contents
    let before = snapshot_generated_files(project_root)
        .context("failed to snapshot generated files before regeneration")?;

    // Step 2: run the generator
    generate::generate_all(project_root);

    // Step 3: snapshot again
    let after = snapshot_generated_files(project_root)
        .context("failed to snapshot generated files after regeneration")?;

    // Step 4: compare
    let mut stale_files: Vec<String> = Vec::new();

    // Check for files that changed or were added
    for (path, new_content) in &after {
        match before.get(path) {
            Some(old_content) if old_content != new_content => {
                stale_files.push(path.clone());
            }
            None => {
                stale_files.push(path.clone());
            }
            _ => {}
        }
    }

    // Check for files that were removed (present before, absent after)
    for path in before.keys() {
        if !after.contains_key(path) {
            stale_files.push(path.clone());
        }
    }

    stale_files.sort();

    // Step 5: report
    if stale_files.is_empty() {
        println!("All generated files are up to date");
        Ok(())
    } else {
        // Restore original contents so we don't leave a dirty tree
        for (path, original_content) in &before {
            let full_path = project_root.join(path);
            if full_path.exists() || !after.contains_key(path) {
                fs::write(&full_path, original_content).with_context(|| {
                    format!("failed to restore original content of {path}")
                })?;
            }
        }
        // Remove files that were newly created by generate but didn't exist before
        for path in &stale_files {
            if !before.contains_key(path) {
                let full_path = project_root.join(path);
                if full_path.exists() {
                    let _ = fs::remove_file(&full_path);
                }
            }
        }

        eprintln!();
        eprintln!("The following generated files are out of date:");
        for path in &stale_files {
            eprintln!("  {path}");
        }
        eprintln!();
        eprintln!("Run `cargo run -p xtask -- generate` to regenerate them.");
        bail!(
            "{} generated file(s) are out of date",
            stale_files.len()
        );
    }
}

/// Collect the contents of all generated .rs files across collection directories.
/// Returns a map from relative path (e.g. "src/matplotlib/viridis.rs") to file contents.
fn snapshot_generated_files(project_root: &Path) -> Result<BTreeMap<String, String>> {
    let src_dir = project_root.join("src");
    let mut snapshot = BTreeMap::new();

    for collection in COLLECTIONS {
        let col_dir = src_dir.join(collection);
        if !col_dir.exists() {
            continue;
        }

        let entries = fs::read_dir(&col_dir)
            .with_context(|| format!("failed to read {}", col_dir.display()))?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();

            // Only consider .rs files
            if path.extension().is_none_or(|ext| ext != "rs") {
                continue;
            }

            let content = fs::read_to_string(&path)
                .with_context(|| format!("failed to read {}", path.display()))?;

            // Only snapshot files that look auto-generated (or mod.rs which is also generated)
            let is_generated = content
                .lines()
                .next()
                .is_some_and(|first_line| first_line.starts_with(GENERATED_PREAMBLE));

            if is_generated {
                let rel_path = path
                    .strip_prefix(project_root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .to_string();
                snapshot.insert(rel_path, content);
            }
        }
    }

    Ok(snapshot)
}
