use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

/// All collection directories that may contain generated .rs files.
const COLLECTIONS: &[&str] = &[
    "matplotlib",
    "crameri",
    "cet",
    "cmocean",
    "colorbrewer",
    "cmasher",
    "ncar",
    "cartocolors",
    "moreland",
    "d3",
];

const GENERATED_PREAMBLE: &str = "// Auto-generated by prismatica xtask";

/// Remove the `data/.cache/` directory.
pub fn clean_cache(project_root: &Path) -> Result<()> {
    let cache_dir = project_root.join("data").join(".cache");
    let mut file_count: u64 = 0;
    let mut total_bytes: u64 = 0;

    if cache_dir.exists() {
        count_dir_contents(&cache_dir, &mut file_count, &mut total_bytes)?;
        fs::remove_dir_all(&cache_dir)
            .with_context(|| format!("failed to remove {}", cache_dir.display()))?;
        println!(
            "Removed data/.cache/ ({} files, {} bytes)",
            file_count, total_bytes
        );
    } else {
        println!("data/.cache/ does not exist, nothing to remove");
    }

    Ok(())
}

/// Remove auto-generated .rs files from src/{collection}/ directories.
/// Never removes mod.rs files.
pub fn clean_generated(project_root: &Path) -> Result<()> {
    let src_dir = project_root.join("src");
    let mut file_count: u64 = 0;
    let mut total_bytes: u64 = 0;

    for collection in COLLECTIONS {
        let col_dir = src_dir.join(collection);
        if !col_dir.exists() {
            continue;
        }

        let entries = fs::read_dir(&col_dir)
            .with_context(|| format!("failed to read {}", col_dir.display()))?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();

            // Only consider .rs files
            if path.extension().is_none_or(|ext| ext != "rs") {
                continue;
            }

            // Never delete mod.rs
            if path.file_name().is_some_and(|name| name == "mod.rs") {
                continue;
            }

            // Check if the file is auto-generated
            if is_generated_file(&path)? {
                let size = entry.metadata()?.len();
                fs::remove_file(&path)
                    .with_context(|| format!("failed to remove {}", path.display()))?;
                file_count += 1;
                total_bytes += size;
            }
        }
    }

    println!(
        "Removed {} generated .rs files ({} bytes)",
        file_count, total_bytes
    );

    Ok(())
}

/// Remove the entire `data/` directory AND all generated .rs files.
pub fn clean_all(project_root: &Path) -> Result<()> {
    let data_dir = project_root.join("data");
    let mut data_file_count: u64 = 0;
    let mut data_total_bytes: u64 = 0;

    if data_dir.exists() {
        count_dir_contents(&data_dir, &mut data_file_count, &mut data_total_bytes)?;
        fs::remove_dir_all(&data_dir)
            .with_context(|| format!("failed to remove {}", data_dir.display()))?;
        println!(
            "Removed data/ ({} files, {} bytes)",
            data_file_count, data_total_bytes
        );
    } else {
        println!("data/ does not exist, nothing to remove");
    }

    clean_generated(project_root)?;

    Ok(())
}

/// Run the clean subcommand based on the provided flags.
pub fn run(project_root: &Path, cache: bool, generated: bool) -> Result<()> {
    if cache && !generated {
        clean_cache(project_root)?;
    } else if generated && !cache {
        clean_generated(project_root)?;
    } else {
        // Both flags set, or neither flag set (default) -- clean everything
        clean_all(project_root)?;
    }

    Ok(())
}

/// Check if a file starts with the auto-generated preamble.
fn is_generated_file(path: &Path) -> Result<bool> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("failed to read {}", path.display()))?;

    Ok(content
        .lines()
        .next()
        .is_some_and(|first_line| first_line.starts_with(GENERATED_PREAMBLE)))
}

/// Recursively count files and their total size in a directory.
fn count_dir_contents(dir: &Path, file_count: &mut u64, total_bytes: &mut u64) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            count_dir_contents(&path, file_count, total_bytes)?;
        } else {
            *file_count += 1;
            *total_bytes += entry.metadata()?.len();
        }
    }
    Ok(())
}
