// Auto-generated by prismatica xtask -- do not edit
//! Matplotlib colormaps (viridis, inferno, magma, plasma, cividis, twilight, mako, rocket).
//!
//! The perceptually uniform colormaps designed for matplotlib by
//! Stéfan van der Walt, Nathaniel Smith, and Eric Firing. These are
//! the most widely used scientific colormaps and are recommended as
//! default replacements for rainbow/jet.
//!
//! License: CC0 (public domain).
//!
//! Source: <https://github.com/BIDS/colormap>

mod cividis;
pub use cividis::CIVIDIS;

mod inferno;
pub use inferno::INFERNO;

mod magma;
pub use magma::MAGMA;

mod mako;
pub use mako::MAKO;

mod plasma;
pub use plasma::PLASMA;

mod rocket;
pub use rocket::ROCKET;

mod twilight;
pub use twilight::TWILIGHT;

mod viridis;
pub use viridis::VIRIDIS;

/// All colormaps in the matplotlib collection.
pub static ALL: &[&crate::Colormap] = &[
    &CIVIDIS, &INFERNO, &MAGMA, &MAKO, &PLASMA, &ROCKET, &TWILIGHT, &VIRIDIS,
];
