// Auto-generated by prismatica xtask -- do not edit
//! CET Perceptually Uniform Colour Maps -- 59 colormaps.
//!
//! Linear, diverging, cyclic, rainbow, and isoluminant maps.
//!
//! Peter Kovesi's CET (Centre for Exploration Targeting) colour maps,
//! rigorously designed for perceptual uniformity using the CIEDE2000
//! colour difference formula.
//!
//! License: CC-BY.
//!
//! Source: <https://colorcet.com/>
//!
//! Citation: Kovesi, P. (2015). Good Colour Maps: How to Design Them.
//! <https://arxiv.org/abs/1509.03700>

mod cet_c1;
pub use cet_c1::CET_C1;

mod cet_c1s;
pub use cet_c1s::CET_C1S;

mod cet_c2;
pub use cet_c2::CET_C2;

mod cet_c2s;
pub use cet_c2s::CET_C2S;

mod cet_c3;
pub use cet_c3::CET_C3;

mod cet_c3s;
pub use cet_c3s::CET_C3S;

mod cet_c4;
pub use cet_c4::CET_C4;

mod cet_c4s;
pub use cet_c4s::CET_C4S;

mod cet_c5;
pub use cet_c5::CET_C5;

mod cet_c5s;
pub use cet_c5s::CET_C5S;

mod cet_c6;
pub use cet_c6::CET_C6;

mod cet_c6s;
pub use cet_c6s::CET_C6S;

mod cet_c7;
pub use cet_c7::CET_C7;

mod cet_c7s;
pub use cet_c7s::CET_C7S;

mod cet_cbc1;
pub use cet_cbc1::CET_CBC1;

mod cet_cbc2;
pub use cet_cbc2::CET_CBC2;

mod cet_cbd1;
pub use cet_cbd1::CET_CBD1;

mod cet_cbl1;
pub use cet_cbl1::CET_CBL1;

mod cet_cbl2;
pub use cet_cbl2::CET_CBL2;

mod cet_d01;
pub use cet_d01::CET_D01;

mod cet_d01a;
pub use cet_d01a::CET_D01A;

mod cet_d02;
pub use cet_d02::CET_D02;

mod cet_d03;
pub use cet_d03::CET_D03;

mod cet_d04;
pub use cet_d04::CET_D04;

mod cet_d06;
pub use cet_d06::CET_D06;

mod cet_d07;
pub use cet_d07::CET_D07;

mod cet_d08;
pub use cet_d08::CET_D08;

mod cet_d09;
pub use cet_d09::CET_D09;

mod cet_d10;
pub use cet_d10::CET_D10;

mod cet_d11;
pub use cet_d11::CET_D11;

mod cet_d12;
pub use cet_d12::CET_D12;

mod cet_d13;
pub use cet_d13::CET_D13;

mod cet_i1;
pub use cet_i1::CET_I1;

mod cet_i2;
pub use cet_i2::CET_I2;

mod cet_i3;
pub use cet_i3::CET_I3;

mod cet_l01;
pub use cet_l01::CET_L01;

mod cet_l02;
pub use cet_l02::CET_L02;

mod cet_l03;
pub use cet_l03::CET_L03;

mod cet_l04;
pub use cet_l04::CET_L04;

mod cet_l05;
pub use cet_l05::CET_L05;

mod cet_l06;
pub use cet_l06::CET_L06;

mod cet_l07;
pub use cet_l07::CET_L07;

mod cet_l08;
pub use cet_l08::CET_L08;

mod cet_l09;
pub use cet_l09::CET_L09;

mod cet_l10;
pub use cet_l10::CET_L10;

mod cet_l11;
pub use cet_l11::CET_L11;

mod cet_l12;
pub use cet_l12::CET_L12;

mod cet_l13;
pub use cet_l13::CET_L13;

mod cet_l14;
pub use cet_l14::CET_L14;

mod cet_l15;
pub use cet_l15::CET_L15;

mod cet_l16;
pub use cet_l16::CET_L16;

mod cet_l17;
pub use cet_l17::CET_L17;

mod cet_l18;
pub use cet_l18::CET_L18;

mod cet_l19;
pub use cet_l19::CET_L19;

mod cet_l20;
pub use cet_l20::CET_L20;

mod cet_r1;
pub use cet_r1::CET_R1;

mod cet_r2;
pub use cet_r2::CET_R2;

mod cet_r3;
pub use cet_r3::CET_R3;

mod cet_r4;
pub use cet_r4::CET_R4;

/// All colormaps in the cet collection.
pub static ALL: &[&crate::Colormap] = &[
    &CET_C1, &CET_C1S, &CET_C2, &CET_C2S, &CET_C3, &CET_C3S, &CET_C4, &CET_C4S, &CET_C5, &CET_C5S,
    &CET_C6, &CET_C6S, &CET_C7, &CET_C7S, &CET_CBC1, &CET_CBC2, &CET_CBD1, &CET_CBL1, &CET_CBL2,
    &CET_D01, &CET_D01A, &CET_D02, &CET_D03, &CET_D04, &CET_D06, &CET_D07, &CET_D08, &CET_D09,
    &CET_D10, &CET_D11, &CET_D12, &CET_D13, &CET_I1, &CET_I2, &CET_I3, &CET_L01, &CET_L02,
    &CET_L03, &CET_L04, &CET_L05, &CET_L06, &CET_L07, &CET_L08, &CET_L09, &CET_L10, &CET_L11,
    &CET_L12, &CET_L13, &CET_L14, &CET_L15, &CET_L16, &CET_L17, &CET_L18, &CET_L19, &CET_L20,
    &CET_R1, &CET_R2, &CET_R3, &CET_R4,
];
